<a href="https://colab.research.google.com/github/lokNezMonzter/llm-fine-tuning/blob/develop/text_classification_llama3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Classification On Titanic Dataset By Fine-Tuining Llama3

In [1]:
# Install required packages
!pip install -q unsloth

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.0/277.0 kB 20.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 39.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.4/366.4 kB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.5/31.5 MB 73.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.2/865.2 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.5/156.5 MB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 120.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 104.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 63.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 73.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 43.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 110.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 36.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 123.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.3/128.3 kB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 21.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 120.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 23.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.19 requires torch<2.7,>=1.10, but you have torch 2.7.0 which is incompatible.
tensorflow-metadata 1.17.1 requires protobuf<6.0.0,>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.3 which is incompatible.
torchaudio 2.6.0+cu124 requires torch==2.6.0, but you have torch 2.7.0 which is incompatible.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
ydf 0.12.0 requires protobuf<6.0.0,>=5.29.1, but you have protobuf 3.20.3 which is incompatible.
grpcio-status 1.71.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.3 which is incompatible.

In [3]:
import torch
from unsloth import FastLanguageModel

## Model Configuration And Initial Parameters

In [4]:
# Some basic parameters for model and tokenizer
max_seq_length = 2048
dtype = torch.float16 # for newer GPUs; otherwise keep None
load_in_4_bit = False # for newer GPUs; otherwise keep False

In [7]:
# Initialize the model and tokenizer
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Meta-Llama-3.1-8B",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4_bit
)

==((====))==  Unsloth 2025.6.2: Fast Llama patching. Transformers: 4.52.4.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.557 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/235 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/459 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

## Configuring LoRA Adapters

In [8]:
model = FastLanguageModel.get_peft_model(
    model,
    r=16, # choose any number > 0; recommended values 8, 16, 32, 64, 128
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0, # start with 0 for optimized
    bias="none", # start with none for optimized
    use_gradient_checkpointing="unsloth", # True or "unsloth" for long context
    random_state=3407,
    use_rslora=False, # unsloth supports rank stabilized LoRA
    loftq_config=None # unlsoth supports LoftQ
)

Unsloth 2025.6.2 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

## Data Preparation

We will use the **Titanic Dataset** to fine-tune Llama3-8b to perform text classification. The **Titanic Dataset** is a CSV file with many coloumns.  

The goal is to predict whether passengers managed to survive or perish based on their characteristics (columns)

In [12]:
from datasets import load_dataset

# Load the dataset
dataset = load_dataset(
    "csv",
    data_files="https://huggingface.co/datasets/unsloth/datasets/raw/main/titanic.csv",
    split="train"
)
print(dataset.column_names)

Downloading data:   0%|          | 0.00/61.2k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [14]:
import pandas as pd

df = pd.DataFrame(dataset)
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  None         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  None         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500  None         S

[5 rows x 12 columns]

### Processing Dataset To Function Like ChatGPT

In [15]:
from unsloth import to_sharegpt

# Modify the dataset to sharegpt format
dataset = to_sharegpt(
    dataset,
    merged_prompt = \
        "[[The passenger embarked from {Embarked}.]]"\
        "[[\nThey are {Sex}.]]"\
        "[[\nThey have {Parch} parents and childen.]]"\
        "[[\nThey have {SibSp} siblings and spouses.]]"\
        "[[\nTheir passenger class is {Pclass}.]]"\
        "[[\nTheir age is {Age}.]]"\
        "[[\nThey paid ${Fare} for the trip.]]",
    conversation_extension = 5, # Randomnly combines conversations into 1! Good for long convos
    output_column_name = "Survived",
)

Merging columns:   0%|          | 0/891 [00:00<?, ? examples/s]

Converting to ShareGPT:   0%|          | 0/891 [00:00<?, ? examples/s]

Flattening the indices:   0%|          | 0/891 [00:00<?, ? examples/s]

Flattening the indices:   0%|          | 0/891 [00:00<?, ? examples/s]

Flattening the indices:   0%|          | 0/891 [00:00<?, ? examples/s]

Flattening the indices:   0%|          | 0/891 [00:00<?, ? examples/s]

Flattening the indices:   0%|          | 0/891 [00:00<?, ? examples/s]

Extending conversations:   0%|          | 0/891 [00:00<?, ? examples/s]

In [17]:
from pprint import pprint
pprint(dataset[0])

{'conversations': [{'from': 'human',
                    'value': 'The passenger embarked from S.\n'
                             'They are male.\n'
                             'They have 1 siblings and spouses.\n'
                             'Their passenger class is 3.\n'
                             'Their age is 22.0.\n'
                             'They paid $7.25 for the trip.'},
                   {'from': 'gpt', 'value': '0'},
                   {'from': 'human',
                    'value': 'The passenger embarked from S.\n'
                             'They are male.\n'
                             'They have 1 parents and childen.\n'
                             'They have 1 siblings and spouses.\n'
                             'Their passenger class is 1.\n'
                             'Their age is 52.0.\n'
                             'They paid $79.65 for the trip.'},
                   {'from': 'gpt', 'value': '0'},
                   {'from': 'human',
                    'value': 'The passenger embarked from S.\n'
                             'They are female.\n'
                             'They have 2 parents and childen.\n'
                             'They have 4 siblings and spouses.\n'
                             'Their passenger class is 3.\n'
                             'Their age is 9.0.\n'
                             'They paid $31.275 for the trip.'},
                   {'from': 'gpt', 'value': '0'},
                   {'from': 'human',
                    'value': 'The passenger embarked from C.\n'
                             'They are male.\n'
                             'Their passenger class is 3.\n'
                             'They paid $7.8958 for the trip.'},
                   {'from': 'gpt', 'value': '0'},
                   {'from': 'human',
                    'value': 'The passenger embarked from S.\n'
                             'They are female.\n'
                             'Their passenger class is 2.\n'
                             'Their age is 24.0.\n'
                             'They paid $13.0 for the trip.'},
                   {'from': 'gpt', 'value': '0'}]}

In [18]:
from unsloth import standardize_sharegpt

# Standardize the sharegpt format
dataset = standardize_sharegpt(dataset)

Unsloth: Standardizing formats (num_proc=12):   0%|          | 0/891 [00:00<?, ? examples/s]

In [19]:
pprint(dataset[0])

{'conversations': [{'content': 'The passenger embarked from S.\n'
                               'They are male.\n'
                               'They have 1 siblings and spouses.\n'
                               'Their passenger class is 3.\n'
                               'Their age is 22.0.\n'
                               'They paid $7.25 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are male.\n'
                               'They have 1 parents and childen.\n'
                               'They have 1 siblings and spouses.\n'
                               'Their passenger class is 1.\n'
                               'Their age is 52.0.\n'
                               'They paid $79.65 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are female.\n'
                               'They have 2 parents and childen.\n'
                               'They have 4 siblings and spouses.\n'
                               'Their passenger class is 3.\n'
                               'Their age is 9.0.\n'
                               'They paid $31.275 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from C.\n'
                               'They are male.\n'
                               'Their passenger class is 3.\n'
                               'They paid $7.8958 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are female.\n'
                               'Their passenger class is 2.\n'
                               'Their age is 24.0.\n'
                               'They paid $13.0 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'}]}

## Prepare Chat Template

In [20]:
chat_template = """Below describes some details about some passengers who went on the Titanic.
Predict whether they survived or perished based on their characteristics.
Output 1 if they survived, and 0 if they died.
>>> Passenger Details:
{INPUT}
>>> Did they survive?
{OUTPUT}"""

In [21]:
from unsloth import apply_chat_template

# Apply the prepared chat template to the dataset
dataset = apply_chat_template(
    dataset,
    tokenizer=tokenizer,
    chat_template=chat_template
)

Unsloth: We automatically added an EOS token to stop endless generations.

Map:   0%|          | 0/891 [00:00<?, ? examples/s]

In [22]:
pprint(dataset[0])

{'conversations': [{'content': 'The passenger embarked from S.\n'
                               'They are male.\n'
                               'They have 1 siblings and spouses.\n'
                               'Their passenger class is 3.\n'
                               'Their age is 22.0.\n'
                               'They paid $7.25 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are male.\n'
                               'They have 1 parents and childen.\n'
                               'They have 1 siblings and spouses.\n'
                               'Their passenger class is 1.\n'
                               'Their age is 52.0.\n'
                               'They paid $79.65 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are female.\n'
                               'They have 2 parents and childen.\n'
                               'They have 4 siblings and spouses.\n'
                               'Their passenger class is 3.\n'
                               'Their age is 9.0.\n'
                               'They paid $31.275 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from C.\n'
                               'They are male.\n'
                               'Their passenger class is 3.\n'
                               'They paid $7.8958 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'},
                   {'content': 'The passenger embarked from S.\n'
                               'They are female.\n'
                               'Their passenger class is 2.\n'
                               'Their age is 24.0.\n'
                               'They paid $13.0 for the trip.',
                    'role': 'user'},
                   {'content': '0', 'role': 'assistant'}],
 'text': '<|begin_of_text|>Below describes some details about some passengers '
         'who went on the Titanic.\n'
         'Predict whether they survived or perished based on their '
         'characteristics.\n'
         'Output 1 if they survived, and 0 if they died.\n'
         '>>> Passenger Details:\n'
         'The passenger embarked from S.\n'
         'They are male.\n'
         'They have 1 siblings and spouses.\n'
         'Their passenger class is 3.\n'
         'Their age is 22.0.\n'
         'They paid $7.25 for the trip.\n'
         '>>> Did they survive?\n'
         '0<|end_of_text|>\n'
         '>>> Passenger Details:\n'
         'The passenger embarked from S.\n'
         'They are male.\n'
         'They have 1 parents and childen.\n'
         'They have 1 siblings and spouses.\n'
         'Their passenger class is 1.\n'
         'Their age is 52.0.\n'
         'They paid $79.65 for the trip.\n'
         '>>> Did they survive?\n'
         '0<|end_of_text|>\n'
         '>>> Passenger Details:\n'
         'The passenger embarked from S.\n'
         'They are female.\n'
         'They have 2 parents and childen.\n'
         'They have 4 siblings and spouses.\n'
         'Their passenger class is 3.\n'
         'Their age is 9.0.\n'
         'They paid $31.275 for the trip.\n'
         '>>> Did they survive?\n'
         '0<|end_of_text|>\n'
         '>>> Passenger Details:\n'
         'The passenger embarked from C.\n'
         'They are male.\n'
         'Their passenger class is 3.\n'
         'They paid $7.8958 for the trip.\n'
         '>>> Did they survive?\n'
         '0<|end_of_text|>\n'
         '>>> Passenger Details:\n'
         'The passenger embarked from S.\n'
         'They are female.\n'
         'Their passenger class is 2.\n'
         'Their age is 24.0.\n'
         'They paid $13.0 for the trip.\n'
         '>>> Did they survive?\n'
         '0<|end_of_text|>'}

## Train The Model

In [24]:
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

In [26]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = True,
        bf16 = False,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

Unsloth: Tokenizing ["text"]:   0%|          | 0/891 [00:00<?, ? examples/s]

### Show Current Memory Stats

In [27]:
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA A100-SXM4-40GB. Max memory = 39.557 GB.
15.998 GB of memory reserved.

In [28]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 891 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/8,072,204,288 (0.52% trained)
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: 93anishpal (93anishpal-iqvia) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Unsloth: Will smartly offload gradients to save VRAM!

/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

### Show Final Memory And Time Stats

In [29]:
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory         /max_memory*100, 3)
lora_percentage = round(used_memory_for_lora/max_memory*100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training.")
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

177.848 seconds used for training.
2.96 minutes used for training.
Peak reserved memory = 16.146 GB.
Peak reserved memory for training = 0.148 GB.
Peak reserved memory % of max memory = 40.817 %.
Peak reserved memory for training % of max memory = 0.374 %.

## Inference

In [30]:
FastLanguageModel.for_inference(model)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(128256, 4096, padding_idx=128004)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=14336, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=14336, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
    )
  )
)

In [34]:
# An example for inferencing
messages = [
    {"role": "user", "content": 'The passenger embarked from S.\n'\
                                'They are male.\n'\
                                'They have 1 siblings and spouses.\n'\
                                'Their passenger class is 3.\n'\
                                'Their age is 22.0.\n'\
                                'They paid $7.25 for the trip.'},
]

input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer

text_streamer = TextStreamer(tokenizer, skip_prompt=True, use_reentrant=False)
_ = model.generate(
    input_ids,
    streamer=text_streamer,
    max_new_tokens=128,
    pad_token_id=tokenizer.eos_token_id,
)

0<|end_of_text|>

In [35]:
# Another example for inferencing
messages = [
    {"role": "user", "content": 'Their passenger class is 1.\n'\
                                'Their age is 22.0.\n'\
                                'They paid $107.25 for the trip.'},
]

input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer

text_streamer = TextStreamer(tokenizer, skip_prompt=True, use_reentrant=False)
_ = model.generate(
    input_ids,
    streamer=text_streamer,
    max_new_tokens=128,
    pad_token_id=tokenizer.eos_token_id,
)

1<|end_of_text|>

## Saving And Loading Finetuned Models

In [37]:
# Save the model and LoRA adapters for inferencing/further fine tuning later on

# model.save_pretrained("lora_model") # Local saving
# tokenizer.save_pretrained("lora_model")
# model.push_to_hub("your_name/lora_model", token = "...") # Online saving
# tokenizer.push_to_hub("your_name/lora_model", token = "...") # Online saving

In [38]:
# Load the model for inferencing

# if False:
#     from unsloth import FastLanguageModel
#     model, tokenizer = FastLanguageModel.from_pretrained(
#         model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
#         max_seq_length = max_seq_length,
#         dtype = dtype,
#         load_in_4bit = load_in_4bit,
#     )
#     FastLanguageModel.for_inference(model) # Enable native 2x faster inference
# pass

# messages = [
#     {"role": "user", "content": 'Their passenger class is 3.\n'\
#                                 'Their age is 22.0.\n'\
#                                 'They paid $107.25 for the trip.'},
# ]
# input_ids = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt = True,
#     return_tensors = "pt",
# ).to("cuda")

# from transformers import TextStreamer
# text_streamer = TextStreamer(tokenizer, skip_prompt = True)
# _ = model.generate(input_ids, streamer = text_streamer, max_new_tokens = 128, pad_token_id = tokenizer.eos_token_id)